version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diyor938
      POSTGRES_DB: deliveryapp
    ports:
      - "5432:5432"
  auth-service:
    build: ./auth-service
    depends_on:
      - postgres
    environment:
      JWT_SECRET: your_jwt_secret
  product-service:
    build: ./product-service
    depends_on:
      - postgres
  order-service:
    build: ./order-service
    depends_on:
      - postgres
  courier-service:
    build: ./courier-service
    depends_on:
      - postgres
  notification-service:
    build: ./notification-service
